version: '3.3'
services:
  apisrestdb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'apisrest'
      MYSQL_USER: 'apisrest'
      MYSQL_PASSWORD: 'ci0156!'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - apisrest-db-volume:/var/lib/mysql
volumes:
  apisrest-db-volume:
